"""empty message

Revision ID: 8704062bfd77
Revises: a8354f8b2f7a
Create Date: 2020-05-26 12:50:07.772109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8704062bfd77'
down_revision = 'a8354f8b2f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'deleted')
    # ### end Alembic commands ###
