"""third one

Revision ID: a8354f8b2f7a
Revises: a56b21ff79bb
Create Date: 2020-05-21 12:04:10.690118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8354f8b2f7a'
down_revision = 'a56b21ff79bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_document_assoc',
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_document_assoc')
    op.drop_table('document')
    # ### end Alembic commands ###
